---
vagrant_synced_folder_default_type: rsync
vagrant_hostname: dgpubs.dev
vagrant_machine_name: dgpubs
vagrant_ip: 192.168.88.8
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: rsync
    create: true

